/**
 * Demo data seeder for dev bypass mode.
 *
 * Generates a realistic hospitality estate: 2 properties (hotel + restaurant),
 * multiple outlets, departments, rooms, tables, menu items, and sample bookings.
 * All data is client-side only — no Supabase writes.
 */

import type {
  Department,
  Organization,
  Outlet,
  Property,
} from "@/domain/identity/types";

export type DemoEstate = {
  organization: Organization;
  properties: Property[];
  outlets: Outlet[];
  departments: Department[];
};

/** Seed a complete demo estate for the dev bypass. */
export function seedDemoEstate(): DemoEstate {
  const organization: Organization = {
    id: "demo-org",
    name: "Amrut Nivaas Demo",
    legalName: "Amrut Nivaas Hospitality Pvt Ltd",
    displayName: "Amrut Nivaas",
    code: "DEMO",
    slug: "amrut-nivaas-demo",
    businessTypes: ["HOTEL", "RESTAURANT"],
    status: "ACTIVE",
    country: "IN",
    currency: "INR",
    timezone: "Asia/Kolkata",
    locale: "en-IN",
    taxRegion: null,
    phone: "+91-20-26050000",
    email: "demo@amrutnivaas.com",
    website: "https://amrutnivaas.com",
    logoUrl: null,
    isDemo: true,
    version: 1,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    archivedAt: null,
  };

  const hotelProperty: Property = {
    id: "prop-hotel",
    organizationId: organization.id,
    name: "Amrut Nivaas Hotel",
    displayName: "Main Hotel",
    code: "HOTEL",
    slug: "amrut-nivaas-hotel",
    type: "HOTEL",
    status: "ACTIVE",
    addressLine1: "123 FC Road",
    addressLine2: "Shivajinagar",
    city: "Pune",
    state: "Maharashtra",
    postalCode: "411005",
    country: "IN",
    phone: "+91-20-26050001",
    email: "hotel@amrutnivaas.com",
    timezone: "Asia/Kolkata",
    currency: "INR",
    locale: "en-IN",
    businessDayStart: "00:00",
    taxProfileId: null,
    version: 1,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    archivedAt: null,
  };

  const restaurantProperty: Property = {
    id: "prop-restaurant",
    organizationId: organization.id,
    name: "Amrut Nivaas Restaurant",
    displayName: "Fine Dining",
    code: "REST",
    slug: "amrut-nivaas-restaurant",
    type: "RESTAURANT",
    status: "ACTIVE",
    addressLine1: "456 JM Road",
    addressLine2: "Deccan Gymkhana",
    city: "Pune",
    state: "Maharashtra",
    postalCode: "411004",
    country: "IN",
    phone: "+91-20-26050002",
    email: "restaurant@amrutnivaas.com",
    timezone: "Asia/Kolkata",
    currency: "INR",
    locale: "en-IN",
    businessDayStart: "00:00",
    taxProfileId: null,
    version: 1,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    archivedAt: null,
  };

  const hotelOutlets: Outlet[] = [
    {
      id: "out-lobby-lounge",
      organizationId: organization.id,
      propertyId: hotelProperty.id,
      name: "Lobby Lounge",
      code: "LOBBY",
      slug: "lobby-lounge",
      type: "RESTAURANT",
      status: "ACTIVE",
      businessHours: {
        monday: { open: "06:00", close: "23:00" },
        tuesday: { open: "06:00", close: "23:00" },
        wednesday: { open: "06:00", close: "23:00" },
        thursday: { open: "06:00", close: "23:00" },
        friday: { open: "06:00", close: "00:00" },
        saturday: { open: "06:00", close: "00:00" },
        sunday: { open: "06:00", close: "23:00" },
      },
      phone: "+91-20-26050010",
      email: "lobby@amrutnivaas.com",
      version: 1,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
      archivedAt: null,
    },
    {
      id: "out-rooftop-bar",
      organizationId: organization.id,
      propertyId: hotelProperty.id,
      name: "Rooftop Bar",
      code: "ROOF",
      slug: "rooftop-bar",
      type: "BAR",
      status: "ACTIVE",
      businessHours: {
        monday: { open: "17:00", close: "01:00" },
        tuesday: { open: "17:00", close: "01:00" },
        wednesday: { open: "17:00", close: "01:00" },
        thursday: { open: "17:00", close: "01:00" },
        friday: { open: "17:00", close: "02:00" },
        saturday: { open: "17:00", close: "02:00" },
        sunday: { open: "17:00", close: "01:00" },
      },
      phone: "+91-20-26050011",
      email: "rooftop@amrutnivaas.com",
      version: 1,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
      archivedAt: null,
    },
  ];

  const restaurantOutlets: Outlet[] = [
    {
      id: "out-main-dining",
      organizationId: organization.id,
      propertyId: restaurantProperty.id,
      name: "Main Dining Hall",
      code: "MAIN",
      slug: "main-dining",
      type: "RESTAURANT",
      status: "ACTIVE",
      businessHours: {
        monday: { open: "12:00", close: "23:00" },
        tuesday: { open: "12:00", close: "23:00" },
        wednesday: { open: "12:00", close: "23:00" },
        thursday: { open: "12:00", close: "23:00" },
        friday: { open: "12:00", close: "00:00" },
        saturday: { open: "12:00", close: "00:00" },
        sunday: { open: "12:00", close: "23:00" },
      },
      phone: "+91-20-26050020",
      email: "dining@amrutnivaas.com",
      version: 1,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
      archivedAt: null,
    },
    {
      id: "out-private-room",
      organizationId: organization.id,
      propertyId: restaurantProperty.id,
      name: "Private Dining Room",
      code: "PVT",
      slug: "private-dining",
      type: "BANQUET",
      status: "ACTIVE",
      businessHours: {
        monday: { open: "12:00", close: "23:00" },
        tuesday: { open: "12:00", close: "23:00" },
        wednesday: { open: "12:00", close: "23:00" },
        thursday: { open: "12:00", close: "23:00" },
        friday: { open: "12:00", close: "00:00" },
        saturday: { open: "12:00", close: "00:00" },
        sunday: { open: "12:00", close: "23:00" },
      },
      phone: "+91-20-26050021",
      email: "private@amrutnivaas.com",
      version: 1,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
      archivedAt: null,
    },
  ];

  const hotelDepartments: Department[] = [
    {
      id: "dept-front-office",
      organizationId: organization.id,
      propertyId: hotelProperty.id,
      outletId: null,
      name: "Front Office",
      code: "FO",
      slug: "front-office",
      status: "ACTIVE",
      version: 1,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
    },
    {
      id: "dept-housekeeping",
      organizationId: organization.id,
      propertyId: hotelProperty.id,
      outletId: null,
      name: "Housekeeping",
      code: "HK",
      slug: "housekeeping",
      status: "ACTIVE",
      version: 1,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
    },
    {
      id: "dept-food-beverage",
      organizationId: organization.id,
      propertyId: hotelProperty.id,
      outletId: null,
      name: "Food & Beverage",
      code: "FB",
      slug: "food-beverage",
      status: "ACTIVE",
      version: 1,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
    },
    {
      id: "dept-kitchen",
      organizationId: organization.id,
      propertyId: hotelProperty.id,
      outletId: null,
      name: "Kitchen",
      code: "KITCHEN",
      slug: "kitchen",
      status: "ACTIVE",
      version: 1,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
    },
    {
      id: "dept-maintenance",
      organizationId: organization.id,
      propertyId: hotelProperty.id,
      outletId: null,
      name: "Maintenance",
      code: "MAINT",
      slug: "maintenance",
      status: "ACTIVE",
      version: 1,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
    },
  ];

  const restaurantDepartments: Department[] = [
    {
      id: "dept-restaurant-foh",
      organizationId: organization.id,
      propertyId: restaurantProperty.id,
      outletId: null,
      name: "Front of House",
      code: "FOH",
      slug: "restaurant-foh",
      status: "ACTIVE",
      version: 1,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
    },
    {
      id: "dept-restaurant-kitchen",
      organizationId: organization.id,
      propertyId: restaurantProperty.id,
      outletId: null,
      name: "Kitchen",
      code: "KITCHEN",
      slug: "restaurant-kitchen",
      status: "ACTIVE",
      version: 1,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
    },
    {
      id: "dept-restaurant-bar",
      organizationId: organization.id,
      propertyId: restaurantProperty.id,
      outletId: null,
      name: "Bar",
      code: "BAR",
      slug: "restaurant-bar",
      status: "ACTIVE",
      version: 1,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
    },
  ];

  return {
    organization,
    properties: [hotelProperty, restaurantProperty],
    outlets: [...hotelOutlets, ...restaurantOutlets],
    departments: [...hotelDepartments, ...restaurantDepartments],
  };
}
