/**
 * Setting definitions registry (Prompt #25).
 *
 * Central registry of all configurable settings in AMRUT NIVAAS.
 * Each setting has metadata: key, name, description, category, data type,
 * default value, supported scopes, validation rules, and sensitivity.
 *
 * This is the single source of truth for what settings exist.
 */

import type { SettingDefinition } from "./types";

export const SETTING_DEFINITIONS: readonly SettingDefinition[] = [
  // =================================================================== GENERAL
  {
    key: "general.dateFormat",
    name: "Date Format",
    description: "Default date display format",
    category: "GENERAL",
    dataType: "ENUM",
    defaultValue: "YYYY-MM-DD",
    scope: ["ORGANIZATION", "PROPERTY"],
    enumValues: ["YYYY-MM-DD", "DD-MM-YYYY", "MM-DD-YYYY", "DD/MM/YYYY"],
    sensitivity: "NORMAL",
    status: "ACTIVE",
    requiresReason: false,
  },
  {
    key: "general.timeFormat",
    name: "Time Format",
    description: "Default time display format",
    category: "GENERAL",
    dataType: "ENUM",
    defaultValue: "24H",
    scope: ["ORGANIZATION", "PROPERTY"],
    enumValues: ["12H", "24H"],
    sensitivity: "NORMAL",
    status: "ACTIVE",
    requiresReason: false,
  },
  {
    key: "general.weekStartDay",
    name: "Week Start Day",
    description: "First day of the week",
    category: "GENERAL",
    dataType: "ENUM",
    defaultValue: "MONDAY",
    scope: ["ORGANIZATION", "PROPERTY"],
    enumValues: ["SUNDAY", "MONDAY", "SATURDAY"],
    sensitivity: "NORMAL",
    status: "ACTIVE",
    requiresReason: false,
  },
  {
    key: "general.timezone",
    name: "Timezone",
    description: "Default timezone for the organization",
    category: "GENERAL",
    dataType: "STRING",
    defaultValue: "Asia/Kolkata",
    scope: ["ORGANIZATION"],
    sensitivity: "NORMAL",
    status: "ACTIVE",
    requiresReason: false,
  },
  {
    key: "general.currency",
    name: "Default Currency",
    description: "Default currency for financial operations",
    category: "GENERAL",
    dataType: "ENUM",
    defaultValue: "INR",
    scope: ["ORGANIZATION"],
    enumValues: ["INR", "USD", "EUR", "GBP"],
    sensitivity: "NORMAL",
    status: "ACTIVE",
    requiresReason: false,
  },

  // =================================================================== BUSINESS
  {
    key: "business.dayStartTime",
    name: "Business Day Start Time",
    description: "Time when business day starts (for overnight operations)",
    category: "BUSINESS",
    dataType: "STRING",
    defaultValue: "06:00",
    scope: ["ORGANIZATION", "PROPERTY"],
    sensitivity: "NORMAL",
    status: "ACTIVE",
    requiresReason: false,
  },

  // =================================================================== RESTAURANT
  {
    key: "restaurant.allowNegativeQuantity",
    name: "Allow Negative Quantity",
    description: "Allow negative quantities in orders (for corrections)",
    category: "RESTAURANT",
    dataType: "BOOLEAN",
    defaultValue: false,
    scope: ["ORGANIZATION", "PROPERTY", "OUTLET"],
    sensitivity: "SENSITIVE",
    status: "ACTIVE",
    requiresReason: false,
  },
  {
    key: "restaurant.requireManagerForDiscount",
    name: "Require Manager Approval for Discount",
    description: "Require manager approval for discounts above threshold",
    category: "RESTAURANT",
    dataType: "BOOLEAN",
    defaultValue: true,
    scope: ["ORGANIZATION", "PROPERTY", "OUTLET"],
    sensitivity: "SENSITIVE",
    status: "ACTIVE",
    requiresReason: false,
  },
  {
    key: "restaurant.maximumDiscountPercentage",
    name: "Maximum Discount Percentage",
    description: "Maximum discount percentage allowed without special approval",
    category: "RESTAURANT",
    dataType: "DECIMAL",
    defaultValue: 10,
    scope: ["ORGANIZATION", "PROPERTY", "OUTLET"],
    validation: { min: 0, max: 100 },
    sensitivity: "SENSITIVE",
    status: "ACTIVE",
    requiresReason: false,
  },
  {
    key: "restaurant.requireReasonForVoid",
    name: "Require Reason for Void",
    description: "Require reason when voiding order items",
    category: "RESTAURANT",
    dataType: "BOOLEAN",
    defaultValue: true,
    scope: ["ORGANIZATION", "PROPERTY", "OUTLET"],
    sensitivity: "NORMAL",
    status: "ACTIVE",
    requiresReason: false,
  },
  {
    key: "restaurant.allowTableTransfer",
    name: "Allow Table Transfer",
    description: "Allow transferring orders between tables",
    category: "RESTAURANT",
    dataType: "BOOLEAN",
    defaultValue: true,
    scope: ["ORGANIZATION", "PROPERTY", "OUTLET"],
    sensitivity: "NORMAL",
    status: "ACTIVE",
    requiresReason: false,
  },
  {
    key: "restaurant.allowSplitBill",
    name: "Allow Split Bill",
    description: "Allow splitting bills across multiple payments",
    category: "RESTAURANT",
    dataType: "BOOLEAN",
    defaultValue: true,
    scope: ["ORGANIZATION", "PROPERTY", "OUTLET"],
    sensitivity: "NORMAL",
    status: "ACTIVE",
    requiresReason: false,
  },
  {
    key: "restaurant.autoPrintKOT",
    name: "Auto Print KOT",
    description: "Automatically print KOT when order is placed",
    category: "RESTAURANT",
    dataType: "BOOLEAN",
    defaultValue: false,
    scope: ["ORGANIZATION", "PROPERTY", "OUTLET"],
    sensitivity: "NORMAL",
    status: "ACTIVE",
    requiresReason: false,
  },
  {
    key: "restaurant.autoPrintReceipt",
    name: "Auto Print Receipt",
    description: "Automatically print receipt on payment",
    category: "RESTAURANT",
    dataType: "BOOLEAN",
    defaultValue: false,
    scope: ["ORGANIZATION", "PROPERTY", "OUTLET"],
    sensitivity: "NORMAL",
    status: "ACTIVE",
    requiresReason: false,
  },

  // =================================================================== HOTEL
  {
    key: "hotel.checkInTime",
    name: "Check-in Time",
    description: "Standard check-in time",
    category: "HOTEL",
    dataType: "STRING",
    defaultValue: "14:00",
    scope: ["ORGANIZATION", "PROPERTY"],
    sensitivity: "NORMAL",
    status: "ACTIVE",
    requiresReason: false,
  },
  {
    key: "hotel.checkOutTime",
    name: "Check-out Time",
    description: "Standard check-out time",
    category: "HOTEL",
    dataType: "STRING",
    defaultValue: "11:00",
    scope: ["ORGANIZATION", "PROPERTY"],
    sensitivity: "NORMAL",
    status: "ACTIVE",
    requiresReason: false,
  },
  {
    key: "hotel.earlyCheckInPolicy",
    name: "Early Check-in Policy",
    description: "Policy for early check-in requests",
    category: "HOTEL",
    dataType: "ENUM",
    defaultValue: "REQUIRE_APPROVAL",
    scope: ["ORGANIZATION", "PROPERTY"],
    enumValues: ["ALLOW", "REQUIRE_APPROVAL", "CHARGE_EXTRA", "BLOCK"],
    sensitivity: "NORMAL",
    status: "ACTIVE",
    requiresReason: false,
  },
  {
    key: "hotel.lateCheckoutPolicy",
    name: "Late Checkout Policy",
    description: "Policy for late checkout requests",
    category: "HOTEL",
    dataType: "ENUM",
    defaultValue: "REQUIRE_APPROVAL",
    scope: ["ORGANIZATION", "PROPERTY"],
    enumValues: ["ALLOW", "REQUIRE_APPROVAL", "CHARGE_EXTRA", "BLOCK"],
    sensitivity: "NORMAL",
    status: "ACTIVE",
    requiresReason: false,
  },
  {
    key: "hotel.allowWalkIn",
    name: "Allow Walk-in Guests",
    description: "Allow check-in without prior reservation",
    category: "HOTEL",
    dataType: "BOOLEAN",
    defaultValue: true,
    scope: ["ORGANIZATION", "PROPERTY"],
    sensitivity: "NORMAL",
    status: "ACTIVE",
    requiresReason: false,
  },
  {
    key: "hotel.requireGuestIdentity",
    name: "Require Guest Identity",
    description: "Require government ID for check-in",
    category: "HOTEL",
    dataType: "BOOLEAN",
    defaultValue: true,
    scope: ["ORGANIZATION", "PROPERTY"],
    sensitivity: "SENSITIVE",
    status: "ACTIVE",
    requiresReason: false,
  },

  // =================================================================== INVENTORY
  {
    key: "inventory.allowNegativeStock",
    name: "Allow Negative Stock",
    description: "Allow inventory to go negative",
    category: "INVENTORY",
    dataType: "BOOLEAN",
    defaultValue: false,
    scope: ["ORGANIZATION", "PROPERTY"],
    sensitivity: "SENSITIVE",
    status: "ACTIVE",
    requiresReason: false,
  },
  {
    key: "inventory.requireWastageReason",
    name: "Require Wastage Reason",
    description: "Require reason for stock wastage",
    category: "INVENTORY",
    dataType: "BOOLEAN",
    defaultValue: true,
    scope: ["ORGANIZATION", "PROPERTY"],
    sensitivity: "NORMAL",
    status: "ACTIVE",
    requiresReason: false,
  },
  {
    key: "inventory.requireStockAdjustmentReason",
    name: "Require Stock Adjustment Reason",
    description: "Require reason for stock adjustments",
    category: "INVENTORY",
    dataType: "BOOLEAN",
    defaultValue: true,
    scope: ["ORGANIZATION", "PROPERTY"],
    sensitivity: "NORMAL",
    status: "ACTIVE",
    requiresReason: false,
  },
  {
    key: "inventory.costingMethod",
    name: "Inventory Costing Method",
    description: "Method for calculating inventory cost",
    category: "INVENTORY",
    dataType: "ENUM",
    defaultValue: "WEIGHTED_AVERAGE",
    scope: ["ORGANIZATION"],
    enumValues: ["WEIGHTED_AVERAGE"],
    sensitivity: "SENSITIVE",
    status: "ACTIVE",
    requiresReason: true,
  },

  // =================================================================== PROCUREMENT
  {
    key: "procurement.requirePurchaseRequest",
    name: "Require Purchase Request",
    description: "Require purchase request before purchase order",
    category: "PROCUREMENT",
    dataType: "BOOLEAN",
    defaultValue: false,
    scope: ["ORGANIZATION", "PROPERTY"],
    sensitivity: "NORMAL",
    status: "ACTIVE",
    requiresReason: false,
  },
  {
    key: "procurement.requirePOApproval",
    name: "Require PO Approval",
    description: "Require approval for purchase orders",
    category: "PROCUREMENT",
    dataType: "BOOLEAN",
    defaultValue: true,
    scope: ["ORGANIZATION", "PROPERTY"],
    sensitivity: "SENSITIVE",
    status: "ACTIVE",
    requiresReason: false,
  },
  {
    key: "procurement.approvalThreshold",
    name: "PO Approval Threshold",
    description: "Purchase order amount requiring approval",
    category: "PROCUREMENT",
    dataType: "DECIMAL",
    defaultValue: 25000,
    scope: ["ORGANIZATION", "PROPERTY"],
    validation: { min: 0 },
    sensitivity: "SENSITIVE",
    status: "ACTIVE",
    requiresReason: false,
  },
  {
    key: "procurement.allowPartialReceipt",
    name: "Allow Partial Receipt",
    description: "Allow partial receipt of purchase orders",
    category: "PROCUREMENT",
    dataType: "BOOLEAN",
    defaultValue: true,
    scope: ["ORGANIZATION", "PROPERTY"],
    sensitivity: "NORMAL",
    status: "ACTIVE",
    requiresReason: false,
  },

  // =================================================================== FINANCE
  {
    key: "finance.defaultTaxInclusive",
    name: "Default Tax Inclusive",
    description: "Prices include tax by default",
    category: "FINANCE",
    dataType: "BOOLEAN",
    defaultValue: true,
    scope: ["ORGANIZATION"],
    sensitivity: "SENSITIVE",
    status: "ACTIVE",
    requiresReason: true,
  },
  {
    key: "finance.requireExpenseApproval",
    name: "Require Expense Approval",
    description: "Require approval for expenses above threshold",
    category: "FINANCE",
    dataType: "BOOLEAN",
    defaultValue: true,
    scope: ["ORGANIZATION"],
    sensitivity: "SENSITIVE",
    status: "ACTIVE",
    requiresReason: false,
  },
  {
    key: "finance.expenseApprovalThreshold",
    name: "Expense Approval Threshold",
    description: "Expense amount requiring approval",
    category: "FINANCE",
    dataType: "DECIMAL",
    defaultValue: 10000,
    scope: ["ORGANIZATION"],
    validation: { min: 0 },
    sensitivity: "SENSITIVE",
    status: "ACTIVE",
    requiresReason: false,
  },
  {
    key: "finance.allowBackdatedTransactions",
    name: "Allow Backdated Transactions",
    description: "Allow backdated financial transactions",
    category: "FINANCE",
    dataType: "BOOLEAN",
    defaultValue: false,
    scope: ["ORGANIZATION"],
    sensitivity: "CRITICAL",
    status: "ACTIVE",
    requiresReason: true,
  },
  {
    key: "finance.backdatedTransactionLimitDays",
    name: "Backdated Transaction Limit (Days)",
    description: "Maximum days allowed for backdated transactions",
    category: "FINANCE",
    dataType: "INTEGER",
    defaultValue: 7,
    scope: ["ORGANIZATION"],
    validation: { min: 0, max: 365 },
    sensitivity: "CRITICAL",
    status: "ACTIVE",
    requiresReason: true,
  },

  // =================================================================== CRM
  {
    key: "crm.requireCustomerMobile",
    name: "Require Customer Mobile",
    description: "Require mobile number for customer creation",
    category: "CRM",
    dataType: "BOOLEAN",
    defaultValue: false,
    scope: ["ORGANIZATION", "PROPERTY"],
    sensitivity: "NORMAL",
    status: "ACTIVE",
    requiresReason: false,
  },
  {
    key: "crm.allowGuestCustomer",
    name: "Allow Guest Customer",
    description: "Allow guest customer creation",
    category: "CRM",
    dataType: "BOOLEAN",
    defaultValue: true,
    scope: ["ORGANIZATION", "PROPERTY"],
    sensitivity: "NORMAL",
    status: "ACTIVE",
    requiresReason: false,
  },
  {
    key: "crm.feedbackEnabled",
    name: "Feedback Enabled",
    description: "Enable customer feedback collection",
    category: "CRM",
    dataType: "BOOLEAN",
    defaultValue: true,
    scope: ["ORGANIZATION", "PROPERTY"],
    sensitivity: "NORMAL",
    status: "ACTIVE",
    requiresReason: false,
  },
  {
    key: "crm.loyaltyEnabled",
    name: "Loyalty Program Enabled",
    description: "Enable loyalty points program",
    category: "CRM",
    dataType: "BOOLEAN",
    defaultValue: false,
    scope: ["ORGANIZATION"],
    sensitivity: "NORMAL",
    status: "ACTIVE",
    requiresReason: false,
  },

  // =================================================================== EVENTS
  {
    key: "events.quotationApprovalRequired",
    name: "Quotation Approval Required",
    description: "Require approval for event quotations",
    category: "EVENTS",
    dataType: "BOOLEAN",
    defaultValue: true,
    scope: ["ORGANIZATION", "PROPERTY"],
    sensitivity: "SENSITIVE",
    status: "ACTIVE",
    requiresReason: false,
  },
  {
    key: "events.bookingRequiresAdvance",
    name: "Booking Requires Advance",
    description: "Require advance payment for event bookings",
    category: "EVENTS",
    dataType: "BOOLEAN",
    defaultValue: true,
    scope: ["ORGANIZATION", "PROPERTY"],
    sensitivity: "SENSITIVE",
    status: "ACTIVE",
    requiresReason: false,
  },
  {
    key: "events.minimumAdvancePercentage",
    name: "Minimum Advance Percentage",
    description: "Minimum advance payment percentage for events",
    category: "EVENTS",
    dataType: "DECIMAL",
    defaultValue: 25,
    scope: ["ORGANIZATION", "PROPERTY"],
    validation: { min: 0, max: 100 },
    sensitivity: "SENSITIVE",
    status: "ACTIVE",
    requiresReason: false,
  },

  // =================================================================== HR
  {
    key: "hr.attendanceCorrectionRequiresApproval",
    name: "Attendance Correction Requires Approval",
    description: "Require approval for attendance corrections",
    category: "HR",
    dataType: "BOOLEAN",
    defaultValue: true,
    scope: ["ORGANIZATION", "PROPERTY"],
    sensitivity: "SENSITIVE",
    status: "ACTIVE",
    requiresReason: false,
  },
  {
    key: "hr.lateThresholdMinutes",
    name: "Late Threshold (Minutes)",
    description: "Minutes after start time to mark as late",
    category: "HR",
    dataType: "INTEGER",
    defaultValue: 15,
    scope: ["ORGANIZATION", "PROPERTY"],
    validation: { min: 0 },
    sensitivity: "NORMAL",
    status: "ACTIVE",
    requiresReason: false,
  },
  {
    key: "hr.documentExpiryAlerts",
    name: "Document Expiry Alerts",
    description: "Enable alerts for expiring employee documents",
    category: "HR",
    dataType: "BOOLEAN",
    defaultValue: true,
    scope: ["ORGANIZATION"],
    sensitivity: "NORMAL",
    status: "ACTIVE",
    requiresReason: false,
  },

  // =================================================================== COMMERCE
  {
    key: "commerce.publicMenuEnabled",
    name: "Public Menu Enabled",
    description: "Enable public menu access",
    category: "COMMERCE",
    dataType: "BOOLEAN",
    defaultValue: true,
    scope: ["ORGANIZATION", "PROPERTY"],
    sensitivity: "NORMAL",
    status: "ACTIVE",
    requiresReason: false,
  },
  {
    key: "commerce.qrOrderingEnabled",
    name: "QR Ordering Enabled",
    description: "Enable QR code ordering",
    category: "COMMERCE",
    dataType: "BOOLEAN",
    defaultValue: false,
    scope: ["ORGANIZATION", "PROPERTY"],
    sensitivity: "NORMAL",
    status: "ACTIVE",
    requiresReason: false,
  },
  {
    key: "commerce.onlineOrderingEnabled",
    name: "Online Ordering Enabled",
    description: "Enable online ordering",
    category: "COMMERCE",
    dataType: "BOOLEAN",
    defaultValue: false,
    scope: ["ORGANIZATION", "PROPERTY"],
    sensitivity: "NORMAL",
    status: "ACTIVE",
    requiresReason: false,
  },

  // =================================================================== NOTIFICATIONS
  {
    key: "notifications.reservationNotificationsEnabled",
    name: "Reservation Notifications",
    description: "Enable reservation notifications",
    category: "NOTIFICATIONS",
    dataType: "BOOLEAN",
    defaultValue: true,
    scope: ["ORGANIZATION", "PROPERTY"],
    sensitivity: "NORMAL",
    status: "ACTIVE",
    requiresReason: false,
  },
  {
    key: "notifications.lowStockNotificationsEnabled",
    name: "Low Stock Notifications",
    description: "Enable low stock notifications",
    category: "NOTIFICATIONS",
    dataType: "BOOLEAN",
    defaultValue: true,
    scope: ["ORGANIZATION", "PROPERTY"],
    sensitivity: "NORMAL",
    status: "ACTIVE",
    requiresReason: false,
  },
  {
    key: "notifications.documentExpiryNotificationsEnabled",
    name: "Document Expiry Notifications",
    description: "Enable document expiry notifications",
    category: "NOTIFICATIONS",
    dataType: "BOOLEAN",
    defaultValue: true,
    scope: ["ORGANIZATION"],
    sensitivity: "NORMAL",
    status: "ACTIVE",
    requiresReason: false,
  },

  // =================================================================== DOCUMENTS
  {
    key: "documents.autoGenerateInvoice",
    name: "Auto Generate Invoice",
    description: "Automatically generate invoice PDF",
    category: "DOCUMENTS",
    dataType: "BOOLEAN",
    defaultValue: false,
    scope: ["ORGANIZATION", "PROPERTY"],
    sensitivity: "NORMAL",
    status: "ACTIVE",
    requiresReason: false,
  },
  {
    key: "documents.autoGenerateReceipt",
    name: "Auto Generate Receipt",
    description: "Automatically generate receipt PDF",
    category: "DOCUMENTS",
    dataType: "BOOLEAN",
    defaultValue: false,
    scope: ["ORGANIZATION", "PROPERTY"],
    sensitivity: "NORMAL",
    status: "ACTIVE",
    requiresReason: false,
  },

  // =================================================================== SECURITY
  {
    key: "security.sessionTimeout",
    name: "Session Timeout (Minutes)",
    description: "Session timeout in minutes",
    category: "SECURITY",
    dataType: "INTEGER",
    defaultValue: 30,
    scope: ["ORGANIZATION"],
    validation: { min: 5, max: 480 },
    sensitivity: "CRITICAL",
    status: "ACTIVE",
    requiresReason: true,
  },
  {
    key: "security.supportAccessAllowed",
    name: "Support Access Allowed",
    description: "Allow platform support to access organization data",
    category: "SECURITY",
    dataType: "BOOLEAN",
    defaultValue: true,
    scope: ["ORGANIZATION"],
    sensitivity: "CRITICAL",
    status: "ACTIVE",
    requiresReason: true,
  },

  // =================================================================== AI
  {
    key: "ai.aiEnabled",
    name: "AI Features Enabled",
    description: "Enable AI-powered features",
    category: "AI",
    dataType: "BOOLEAN",
    defaultValue: false,
    scope: ["ORGANIZATION"],
    sensitivity: "NORMAL",
    status: "ACTIVE",
    requiresReason: false,
  },
  {
    key: "ai.aiRecommendationsEnabled",
    name: "AI Recommendations Enabled",
    description: "Enable AI recommendations",
    category: "AI",
    dataType: "BOOLEAN",
    defaultValue: false,
    scope: ["ORGANIZATION"],
    sensitivity: "NORMAL",
    status: "ACTIVE",
    requiresReason: false,
  },

  // =================================================================== ENTERPRISE
  {
    key: "enterprise.centralReportingEnabled",
    name: "Central Reporting Enabled",
    description: "Enable central reporting across properties",
    category: "ENTERPRISE",
    dataType: "BOOLEAN",
    defaultValue: false,
    scope: ["ORGANIZATION"],
    sensitivity: "NORMAL",
    status: "ACTIVE",
    requiresReason: false,
  },
  {
    key: "enterprise.centralProcurementEnabled",
    name: "Central Procurement Enabled",
    description: "Enable central procurement across properties",
    category: "ENTERPRISE",
    dataType: "BOOLEAN",
    defaultValue: false,
    scope: ["ORGANIZATION"],
    sensitivity: "NORMAL",
    status: "ACTIVE",
    requiresReason: false,
  },
];

/**
 * Get setting definition by key.
 */
export function getSettingDefinition(key: string): SettingDefinition | null {
  return SETTING_DEFINITIONS.find((s) => s.key === key) ?? null;
}

/**
 * Get all settings for a category.
 */
export function getSettingsByCategory(category: string): SettingDefinition[] {
  return SETTING_DEFINITIONS.filter((s) => s.category === category);
}
